builds:
  - versionName: "3.0.0"
    versionCode: 1
    commit: V3
    subdir: .
    gradle:
      - release
    forceversion: true
    forcevercode: true
    ndk: r21e
    # Especificar versiones exactas para reproducibilidad
    build:
      - echo "Configurando build reproducible..."
      - export ANDROID_NDK_HOME=$ANDROID_NDK
      - export NDK_VERSION=21.4.7075529
      
    # Deshabilitar verificación temporal
    disable: 
      - ReproducibleBuilds 